class Constants:
    '''
    常量
    '''

    #常量
    UNDEFINED_NUMBER = -1
    MAX_NUMBER = 1145141919810
    
    MIN_MAX_USER = 3

    #用户类型
    USER_ROLE_COMMONER = 0
    USER_ROLE_MANAGER = 1
    USER_ROLE_CREATOR = 2

    #错误码
    ERROR_CODE_NOT_STORED = 101
    ERROR_CODE_RECOMMEND = 201
    ERROR_CODE_NO_REASON = 211
    ERROR_CODE_REJECT = 212
    ERROR_CODE_UNKNOWN = 500
    ERROR_CODE_LOGIN_ERROR = 501
    ERROR_CODE_INVALID_PARAMETER = 502
    ERROR_CODE_NOT_FOUND = 503
    ERROR_CODE_INVALID_CHANGE = 504
    ERROR_CODE_LACK_ACCESS = 505
    ERROR_CODE_NETWORK_ERROR = 506
    ERROR_CODE_DENIAL = 507
