# Generated by Django 4.2.5 on 2023-12-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_username_user_openid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Openid", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("session", models.CharField(max_length=100)),
                ("Guardian_Openid", models.CharField(max_length=100)),
                ("Status", models.CharField(default="UNBOUND", max_length=100)),
                ("Name", models.CharField(max_length=100)),
                ("Address", models.CharField(max_length=200)),
                ("Phone_contact", models.CharField(max_length=100)),
                ("Medicine_name", models.CharField(max_length=200)),
                ("Medicine_time", models.CharField(max_length=100)),
                ("Medicine_usage", models.CharField(max_length=400)),
                (
                    "Medicine_status",
                    models.CharField(default="NOTTAKEN", max_length=200),
                ),
            ],
        ),
    ]
