# Generated by Django 4.2.5 on 2023-12-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Openid", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("session", models.CharField(max_length=100)),
                ("Guardian_id", models.CharField(max_length=100)),
                ("Patient_id", models.CharField(default="UNDEFINED", max_length=100)),
                ("Doctor_id", models.CharField(default="UNDEFINED", max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="Guardian_Openid",
            new_name="Patient_id",
        ),
        migrations.AddField(
            model_name="globalvariables",
            name="Guardian_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="globalvariables",
            name="Patient_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="Guardian_id",
            field=models.CharField(default="UNDEFINED", max_length=100),
        ),
        migrations.AlterField(
            model_name="globalvariables",
            name="AppId",
            field=models.CharField(default="UNDEFINED", max_length=100),
        ),
        migrations.AlterField(
            model_name="globalvariables",
            name="SecretId",
            field=models.CharField(default="UNDEFINED", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="Address",
            field=models.CharField(default="UNDEFINED", max_length=200),
        ),
        migrations.AlterField(
            model_name="patient",
            name="Medicine_name",
            field=models.CharField(default="UNDEFINED", max_length=200),
        ),
        migrations.AlterField(
            model_name="patient",
            name="Medicine_time",
            field=models.CharField(default="UNDEFINED", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="Medicine_usage",
            field=models.CharField(default="UNDEFINED", max_length=400),
        ),
        migrations.AlterField(
            model_name="patient",
            name="Name",
            field=models.CharField(default="UNDEFINED", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="Phone_contact",
            field=models.CharField(default="UNDEFINED", max_length=100),
        ),
    ]
