# Generated by Django 4.2.5 on 2023-12-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_patient_medicine_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Openid", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("session", models.CharField(max_length=100)),
                ("Doctor_id", models.CharField(max_length=100)),
                ("Guardian_id_list", models.JSONField(null=True)),
                ("Doctor_info", models.JSONField(null=True)),
                ("Reservation", models.JSONField(null=True)),
                ("Reservation_info", models.JSONField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="Medicine_reminder",
            new_name="Healthdata",
        ),
        migrations.AddField(
            model_name="globalvariables",
            name="Doctor_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guardian",
            name="Reservation",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="guardian",
            name="Status",
            field=models.CharField(default="UNBOUND", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="Medicine",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="Memoir",
            field=models.JSONField(null=True),
        ),
    ]
