# Generated by Django 4.2.5 on 2023-12-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_user_img_alter_user_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaCampTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.FileField(
                        max_length=256, upload_to="camp/", verbose_name="营地图片"
                    ),
                ),
            ],
            options={
                "db_table": "media_camp",
            },
        ),
    ]
