# Generated by Django 4.2.5 on 2023-12-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_mediacamptest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="img",
            field=models.ImageField(null=True, upload_to="info"),
        ),
    ]
